wandb_version: 1

dataset_config:
  desc: null
  value: configs/datasets/caltech-101.yaml
factorization:
  desc: null
  value: sepfpl_time_adaptive
rank:
  desc: null
  value: 16
noise:
  desc: null
  value: 0.01
rdp_alpha:
  desc: null
  value: 2.0
rdp_p:
  desc: null
  value: 1.05
num_users:
  desc: null
  value: 10
round:
  desc: null
  value: 30
seed:
  desc: null
  value: 1
task_id:
  desc: null
  value: '[55/120]'
norm_thresh:
  desc: null
  value: 10.0
lr:
  desc: null
  value: 0.001
train_batch_size:
  desc: null
  value: 32
test_batch_size:
  desc: null
  value: 100
partition:
  desc: null
  value: noniid-labeldir
beta:
  desc: null
  value: 0.3
n_ctx:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.11.14
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1763667940
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 1
      - 13
      - 15
      - 16
      - 23
      4: 3.11.14
      5: 0.17.5
      8:
      - 8
      13: linux-x86_64
